[package]
name = "asm6502-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
lsp-server = "0.7.7"
lsp-types = "0.97.0"
serde_json = "1.0.132"
serde = "1.0.215"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
crossbeam-channel = "0.5"
